/* eslint-disable sort-keys */
const symbolMap = {
	'0': './mana/0.svg',
	'1': './mana/1.svg',
	'2': './mana/2.svg',
	'3': './mana/3.svg',
	'4': './mana/4.svg',
	'5': './mana/5.svg',
	'6': './mana/6.svg',
	'7': './mana/7.svg',
	'8': './mana/8.svg',
	'9': './mana/9.svg',
	'10': './mana/10.svg',
	'11': './mana/11.svg',
	'12': './mana/12.svg',
	'13': './mana/13.svg',
	'14': './mana/14.svg',
	'15': './mana/15.svg',
	X: './mana/X.svg',
	W: './mana/W.svg',
	U: './mana/U.svg',
	B: './mana/B.svg',
	R: './mana/R.svg',
	G: './mana/G.svg',
	C: './mana/C.svg',
	'W/P': './mana/WP.svg',
	'U/P': './mana/UP.svg',
	'B/P': './mana/BP.svg',
	'R/P': './mana/RP.svg',
	'G/P': './mana/GP.svg',
	'W/U': './mana/WU.svg',
	'W/B': './mana/WB.svg',
	'U/B': './mana/UB.svg',
	'U/R': './mana/UR.svg',
	'B/R': './mana/BR.svg',
	'B/G': './mana/BG.svg',
	'R/W': './mana/RW.svg',
	'R/G': './mana/RG.svg',
	'G/W': './mana/GW.svg',
	'G/U': './mana/GU.svg',
	'2W': './mana/2W.svg',
	'2U': './mana/2U.svg',
	'2B': './mana/2B.svg',
	'2R': './mana/2R.svg',
	'2G': './mana/2G.svg',
};

export default symbolMap;
